### ISSUE TITLE
OSError (Permission denied) on import

### ISSUE THREAD

**Issue by smcoll** [oliverseal/python-geonameszip#1]
After pip installing, i cannot import:

```
>>> import geonameszip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.virtualenvs/mine/local/lib/python2.7/site-packages/geonameszip/__init__.py", line 21, in <module>
    os.makedirs(BASE_DIR)
  File "/home/me/.virtualenvs/mine/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/var/lib/geonameszip/'
```

The python process doesn't have write permissions to write to `/var/lib`.

Perhaps it might make sense to set `BASE_DIR` via an environment variable, or to use a tmp location.

**Comment by oliverseal** [comment]
I know a lot more than I used to when I made this. An original implementation of this used /tmp/ but found that some distros treat that truly as temporary will just clean it out from time to time, breaking an app.
